server:
  port: 8088

logging:
  level:
    org.springframework:  DEBUG

spring:
  messages:
    basename: messages
  boot:
    admin:
      client:
        url: http://localhost:8088
        instance:
          service-url: http://localhost:8088

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true


